name: flutter_web_plotly
description: Plotly for Flutter web

publish_to: 'none' 
version: 1.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - js/plotly-latest.min.js

